### ISSUE TITLE
:wave: why the JSON.parse(JSON.stringify(restul)) in utils.js

### ISSUE THREAD

**Issue by gr2m** [ClydeDz/netlify-functions-slack-demo#2]
Hey I'm trying to make slack work in a function environment. I know it's been a while ... but looking through your code I wondered about this line

https://github.com/ClydeDz/netlify-functions-slack-demo/blob/3b5ccd0504511bbf95b2bb1e05f3fabe23d078f6/src/utils.ts#L21

That's quite the performance hit and I wonder why?

Sorry for the random question and blast from the past. Thank you for sharing your example! Much appreciated!

**Comment by ClydeDz** [comment]
Hey @gr2m, apologies for the delayed response. It's been so long that I can't remember why and I'd have to debug it to find out.

**Comment by gr2m** [comment]
I hear you, no worries, asked just in case you can recall. Thank you!
